### ISSUE TITLE
brew_my_mac.sh无法安装应用

### ISSUE THREAD

**Issue by aiiibolo** [jsmjsm/BrewMyMac#1]
backup.sh运行没问题，可以正常生成应用列列表，但是在使用brew_my_mac脚本时提示没有
```cat: cask.list: No such file or directory```
```cat: formulae.list: No such file or directory```
但是这些文件是在对应的位置的

**Comment by jsmjsm** [comment]
收到，我研究一下，感谢反馈。

**Comment by jsmjsm** [comment]
bug 已经修复，请使用最新的脚本进行还原操作。

https://github.com/jsmjsm/BrewMyMac/commit/466667a53d38eb689ab584a25d24cca78220a173

**Comment by aiiibolo** [comment]
收到，多谢
